/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    guests: Guest;
    'bride-guests': BrideGuest;
    'groom-guests': GroomGuest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    guests: GuestsSelect<false> | GuestsSelect<true>;
    'bride-guests': BrideGuestsSelect<false> | BrideGuestsSelect<true>;
    'groom-guests': GroomGuestsSelect<false> | GroomGuestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'wedding-details': WeddingDetail;
    'bride-wedding-details': BrideWeddingDetail;
    'groom-wedding-details': GroomWeddingDetail;
  };
  globalsSelect: {
    'wedding-details': WeddingDetailsSelect<false> | WeddingDetailsSelect<true>;
    'bride-wedding-details': BrideWeddingDetailsSelect<false> | BrideWeddingDetailsSelect<true>;
    'groom-wedding-details': GroomWeddingDetailsSelect<false> | GroomWeddingDetailsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests".
 */
export interface Guest {
  id: number;
  name: string;
  code: string;
  isGeneralInvite?: boolean | null;
  status?: ('pending' | 'confirmed' | 'declined') | null;
  wishes?: string | null;
  numberOfGuests?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bride-guests".
 */
export interface BrideGuest {
  id: number;
  name: string;
  code: string;
  isGeneralInvite?: boolean | null;
  status?: ('pending' | 'confirmed' | 'declined') | null;
  wishes?: string | null;
  numberOfGuests?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groom-guests".
 */
export interface GroomGuest {
  id: number;
  name: string;
  code: string;
  isGeneralInvite?: boolean | null;
  status?: ('pending' | 'confirmed' | 'declined') | null;
  wishes?: string | null;
  numberOfGuests?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'guests';
        value: number | Guest;
      } | null)
    | ({
        relationTo: 'bride-guests';
        value: number | BrideGuest;
      } | null)
    | ({
        relationTo: 'groom-guests';
        value: number | GroomGuest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guests_select".
 */
export interface GuestsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  isGeneralInvite?: T;
  status?: T;
  wishes?: T;
  numberOfGuests?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bride-guests_select".
 */
export interface BrideGuestsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  isGeneralInvite?: T;
  status?: T;
  wishes?: T;
  numberOfGuests?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groom-guests_select".
 */
export interface GroomGuestsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  isGeneralInvite?: T;
  status?: T;
  wishes?: T;
  numberOfGuests?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-details".
 */
export interface WeddingDetail {
  id: number;
  bride: {
    name: string;
    bio?: string | null;
    photo?: (number | null) | Media;
  };
  groom: {
    name: string;
    bio?: string | null;
    photo?: (number | null) | Media;
  };
  timeline?:
    | {
        time: string;
        title: string;
        description?: string | null;
        location?: string | null;
        mapUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  quote?: string | null;
  quoteAuthor?: string | null;
  quoteBackgroundImage?: (number | null) | Media;
  coupleBackgroundImage?: (number | null) | Media;
  ceremony: {
    time: string;
    date: string;
    dayOfWeek?: string | null;
    lunarDate?: string | null;
    venueName: string;
    venueAddress: string;
    mapUrl?: string | null;
  };
  giftConfig?: {
    brideQRCode?: (number | null) | Media;
    groomQRCode?: (number | null) | Media;
  };
  venue: {
    name: string;
    address: string;
    mapUrl?: string | null;
  };
  /**
   * Add custom sections with parallax background images
   */
  customSections?:
    | {
        enabled?: boolean | null;
        title?: string | null;
        content?: string | null;
        backgroundImage?: (number | null) | Media;
        /**
         * Speed of parallax effect (0.1 - 1.0, lower = slower)
         */
        parallaxSpeed?: number | null;
        /**
         * CSS value (e.g., 70vh, 500px)
         */
        minHeight?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select images to display in the "Our Moments" gallery section. If empty, no images will be shown.
   */
  galleryImages?: (number | Media)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bride-wedding-details".
 */
export interface BrideWeddingDetail {
  id: number;
  bride: {
    name: string;
    bio?: string | null;
    photo?: (number | null) | Media;
  };
  groom: {
    name: string;
    bio?: string | null;
    photo?: (number | null) | Media;
  };
  timeline?:
    | {
        time: string;
        title: string;
        description?: string | null;
        location?: string | null;
        mapUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  quote?: string | null;
  quoteAuthor?: string | null;
  quoteBackgroundImage?: (number | null) | Media;
  coupleBackgroundImage?: (number | null) | Media;
  ceremony: {
    time: string;
    date: string;
    dayOfWeek?: string | null;
    lunarDate?: string | null;
    venueName: string;
    venueAddress: string;
    mapUrl?: string | null;
  };
  giftConfig?: {
    brideQRCode?: (number | null) | Media;
    groomQRCode?: (number | null) | Media;
  };
  venue: {
    name: string;
    address: string;
    mapUrl?: string | null;
  };
  /**
   * Add custom sections with parallax background images
   */
  customSections?:
    | {
        enabled?: boolean | null;
        title?: string | null;
        content?: string | null;
        backgroundImage?: (number | null) | Media;
        /**
         * Speed of parallax effect (0.1 - 1.0, lower = slower)
         */
        parallaxSpeed?: number | null;
        /**
         * CSS value (e.g., 70vh, 500px)
         */
        minHeight?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select images to display in the "Our Moments" gallery section. If empty, no images will be shown.
   */
  galleryImages?: (number | Media)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groom-wedding-details".
 */
export interface GroomWeddingDetail {
  id: number;
  bride: {
    name: string;
    bio?: string | null;
    photo?: (number | null) | Media;
  };
  groom: {
    name: string;
    bio?: string | null;
    photo?: (number | null) | Media;
  };
  timeline?:
    | {
        time: string;
        title: string;
        description?: string | null;
        location?: string | null;
        mapUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  quote?: string | null;
  quoteAuthor?: string | null;
  quoteBackgroundImage?: (number | null) | Media;
  coupleBackgroundImage?: (number | null) | Media;
  ceremony: {
    time: string;
    date: string;
    dayOfWeek?: string | null;
    lunarDate?: string | null;
    venueName: string;
    venueAddress: string;
    mapUrl?: string | null;
  };
  giftConfig?: {
    brideQRCode?: (number | null) | Media;
    groomQRCode?: (number | null) | Media;
  };
  venue: {
    name: string;
    address: string;
    mapUrl?: string | null;
  };
  /**
   * Add custom sections with parallax background images
   */
  customSections?:
    | {
        enabled?: boolean | null;
        title?: string | null;
        content?: string | null;
        backgroundImage?: (number | null) | Media;
        /**
         * Speed of parallax effect (0.1 - 1.0, lower = slower)
         */
        parallaxSpeed?: number | null;
        /**
         * CSS value (e.g., 70vh, 500px)
         */
        minHeight?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select images to display in the "Our Moments" gallery section. If empty, no images will be shown.
   */
  galleryImages?: (number | Media)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wedding-details_select".
 */
export interface WeddingDetailsSelect<T extends boolean = true> {
  bride?:
    | T
    | {
        name?: T;
        bio?: T;
        photo?: T;
      };
  groom?:
    | T
    | {
        name?: T;
        bio?: T;
        photo?: T;
      };
  timeline?:
    | T
    | {
        time?: T;
        title?: T;
        description?: T;
        location?: T;
        mapUrl?: T;
        id?: T;
      };
  quote?: T;
  quoteAuthor?: T;
  quoteBackgroundImage?: T;
  coupleBackgroundImage?: T;
  ceremony?:
    | T
    | {
        time?: T;
        date?: T;
        dayOfWeek?: T;
        lunarDate?: T;
        venueName?: T;
        venueAddress?: T;
        mapUrl?: T;
      };
  giftConfig?:
    | T
    | {
        brideQRCode?: T;
        groomQRCode?: T;
      };
  venue?:
    | T
    | {
        name?: T;
        address?: T;
        mapUrl?: T;
      };
  customSections?:
    | T
    | {
        enabled?: T;
        title?: T;
        content?: T;
        backgroundImage?: T;
        parallaxSpeed?: T;
        minHeight?: T;
        id?: T;
      };
  galleryImages?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bride-wedding-details_select".
 */
export interface BrideWeddingDetailsSelect<T extends boolean = true> {
  bride?:
    | T
    | {
        name?: T;
        bio?: T;
        photo?: T;
      };
  groom?:
    | T
    | {
        name?: T;
        bio?: T;
        photo?: T;
      };
  timeline?:
    | T
    | {
        time?: T;
        title?: T;
        description?: T;
        location?: T;
        mapUrl?: T;
        id?: T;
      };
  quote?: T;
  quoteAuthor?: T;
  quoteBackgroundImage?: T;
  coupleBackgroundImage?: T;
  ceremony?:
    | T
    | {
        time?: T;
        date?: T;
        dayOfWeek?: T;
        lunarDate?: T;
        venueName?: T;
        venueAddress?: T;
        mapUrl?: T;
      };
  giftConfig?:
    | T
    | {
        brideQRCode?: T;
        groomQRCode?: T;
      };
  venue?:
    | T
    | {
        name?: T;
        address?: T;
        mapUrl?: T;
      };
  customSections?:
    | T
    | {
        enabled?: T;
        title?: T;
        content?: T;
        backgroundImage?: T;
        parallaxSpeed?: T;
        minHeight?: T;
        id?: T;
      };
  galleryImages?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groom-wedding-details_select".
 */
export interface GroomWeddingDetailsSelect<T extends boolean = true> {
  bride?:
    | T
    | {
        name?: T;
        bio?: T;
        photo?: T;
      };
  groom?:
    | T
    | {
        name?: T;
        bio?: T;
        photo?: T;
      };
  timeline?:
    | T
    | {
        time?: T;
        title?: T;
        description?: T;
        location?: T;
        mapUrl?: T;
        id?: T;
      };
  quote?: T;
  quoteAuthor?: T;
  quoteBackgroundImage?: T;
  coupleBackgroundImage?: T;
  ceremony?:
    | T
    | {
        time?: T;
        date?: T;
        dayOfWeek?: T;
        lunarDate?: T;
        venueName?: T;
        venueAddress?: T;
        mapUrl?: T;
      };
  giftConfig?:
    | T
    | {
        brideQRCode?: T;
        groomQRCode?: T;
      };
  venue?:
    | T
    | {
        name?: T;
        address?: T;
        mapUrl?: T;
      };
  customSections?:
    | T
    | {
        enabled?: T;
        title?: T;
        content?: T;
        backgroundImage?: T;
        parallaxSpeed?: T;
        minHeight?: T;
        id?: T;
      };
  galleryImages?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}